CREATE TABLE MY_EMP_TABLE (
    ID INT,
    LAST_NAME VARCHAR(10),
    FIRST_NAME VARCHAR(10),
    SALARY INT
);

INSERT INTO MY_EMP_TABLE (ID, LAST_NAME, FIRST_NAME, SALARY)
VALUES (1, 'Black', 'John', 1100);

INSERT INTO MY_EMP_TABLE (ID, LAST_NAME, FIRST_NAME, SALARY)
VALUES (2, 'White', 'Kent', 1300);

INSERT INTO MY_EMP_TABLE (ID, LAST_NAME, FIRST_NAME, SALARY)
VALUES (3, 'Orange', 'David', 1700);

INSERT INTO MY_EMP_TABLE (ID, LAST_NAME, FIRST_NAME, SALARY)
VALUES (4, 'Pink', 'Alissa', 1900);

UPDATE MY_EMP_TABLE
SET SALARY = ROUND(SALARY * 1.10);

DELETE FROM MY_EMP_TABLE
WHERE FIRST_NAME = 'David';

TRUNCATE TABLE MY_EMP_TABLE;





